In [1]:
from train import ray_init, build_trainer_config
from config import get_config_test, PPOTrainer
import numpy as np

In [2]:
c = get_config_test()
c['num_workers'] = 0

In [3]:
c_rl = build_trainer_config(c)

Creating agent humanoid_blocker
Reading agent XML from: /home/sergei/git/chai/multiagent-competition/gym_compete/new_envs/assets/humanoid_body.xml
Creating agent humanoid
Reading agent XML from: /home/sergei/git/chai/multiagent-competition/gym_compete/new_envs/assets/humanoid_body.xml
Scene XML path: /home/sergei/git/chai/multiagent-competition/gym_compete/new_envs/assets/world_body.humanoid_body.humanoid_body.xml
Created Scene with agents
Config: env: multicomp
env_config:
  env_name: multicomp/YouShallNotPassHumans-v0
  with_video: false
framework: tfe
kl_coeff: 1.0
local_tf_session_args:
  inter_op_parallelism_threads: 4
  intra_op_parallelism_threads: 4
lr: 0.0001
multiagent:
  policies:
    player_1:
    - <class 'ray.rllib.policy.tf_policy_template.PPOTFPolicy'>
    - Box(380,)
    - Box(17,)
    - framework: tfe
      model:
        fcnet_activation: tanh
        fcnet_hiddens:
        - 64
        - 64
        free_log_std: true
        use_lstm: false
      observation_filter:

In [4]:
trainer = PPOTrainer(c_rl)

Creating agent humanoid_blocker
Reading agent XML from: /home/sergei/git/chai/multiagent-competition/gym_compete/new_envs/assets/humanoid_body.xml
Creating agent humanoid
Reading agent XML from: /home/sergei/git/chai/multiagent-competition/gym_compete/new_envs/assets/humanoid_body.xml
Scene XML path: /home/sergei/git/chai/multiagent-competition/gym_compete/new_envs/assets/world_body.humanoid_body.humanoid_body.xml
Created Scene with agents
The following Variables were used a Lambda layer's call (lambda), but
are not present in its tracked objects:
  <tf.Variable 'player_1/log_std:0' shape=(17,) dtype=float32>
It is possible that this is intended behavior, but it is more likely
an omission. This is a strong indication that this layer should be
formulated as a subclassed Layer rather than a Lambda layer.
Instructions for updating:
Use `tf.cast` instead.
Creating agent humanoid_blocker
Reading agent XML from: /home/sergei/git/chai/multiagent-competition/gym_compete/new_envs/assets/humanoi

Install gputil for GPU system monitoring.


In [5]:
env = trainer.env_creator(c_rl['env_config'])

Creating agent humanoid_blocker
Reading agent XML from: /home/sergei/git/chai/multiagent-competition/gym_compete/new_envs/assets/humanoid_body.xml
Creating agent humanoid
Reading agent XML from: /home/sergei/git/chai/multiagent-competition/gym_compete/new_envs/assets/humanoid_body.xml
Scene XML path: /home/sergei/git/chai/multiagent-competition/gym_compete/new_envs/assets/world_body.humanoid_body.humanoid_body.xml
Created Scene with agents


In [6]:
obs = env.reset()

In [7]:
p = trainer.get_policy('player_2')

In [8]:
p.model.forward(input_dict={'obs': np.array([obs['player_2']])}, state=None, seq_lens=None)


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



(<tf.Tensor: shape=(1, 34), dtype=float32, numpy=
 array([[ 1.0901332 , -2.4825482 ,  1.1352253 , -1.9470645 ,  1.1479528 ,
          0.950797  , -0.14320488, -1.3485874 ,  1.6573427 ,  0.08454831,
         -0.79728556, -0.8633359 , -1.3563421 , -1.4148328 , -1.6738188 ,
          1.0254254 , -0.25747362, -1.1946142 , -1.1943502 , -1.3822243 ,
         -1.2458018 , -1.3420836 , -1.6185255 , -1.7103587 , -1.162646  ,
         -1.3695905 , -1.8137943 , -1.822718  , -0.96715873, -0.9660747 ,
         -0.9697067 , -0.8741934 , -1.0161136 , -0.80789745]],
       dtype=float32)>,
 None)

In [9]:
p.model.value_function()

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([4.2595572], dtype=float32)>